### ISSUE TITLE
ASI / SI 

### ISSUE THREAD

**Issue by thegamecat** [joosthoeks/jhTAlib#10]
Tried using ASI, it has a couple of issues where R is not set which can happen so I made a tweak:

```
def SI(df, L):
    """
    Swing Index (J. Welles Wilder)
    """
    si_list = []
    i = 0
    R = 0
    while i < len(df['Close']):
        if i < 1 or df['High'][i] - df['Low'][i] == 0:
            si = float('NaN')
        else:
            N = (df['Close'][i] - df['Close'][i - 1]) + (.5 * (df['Close'][i] - df['Open'][i])) + (.25 *(df['Close'][i - 1] - df['Open'][i - 1]))
            R1 = df['High'][i] - df['Close'][i - 1]
            R2 = df['Low'][i] - df['Close'][i - 1]
            R3 = df['High'][i] - df['Low'][i]
            if R1 > R2 and R1 > R3:
                R = (df['High'][i] - df['Close'][i - 1]) - (.5 * (df['Low'][i] - df['Close'][i - 1])) + (.25 * (df['Close'][i - 1] - df['Open'][i - 1]))
            if R2 > R1 and R2 > R3:
                R = (df['Low'][i] - df['Close'][i - 1]) - (.5 * (df['High'][i] - df['Close'][i - 1])) + (.25 * (df['Close'][i - 1] - df['Open'][i - 1]))
            if R3 > R1 and R3 > R2:
                R = (df['High'][i] - df['Low'][i]) + (.25 * (df['Close'][i - 1] - df['Open'][i - 1]))
            K1 = df['High'][i] - df['Close'][i - 1]
            K2 = df['Low'][i] - df['Close'][i - 1]
            if K1 > K2:
                K = K1
            else:
                K = K2
            if R==0:
            	si = float('NaN')
            else:
            	si = 50 * (N / R) * (K / L)
        si_list.append(si)
        i += 1
    return si_list
```

The issue I see is the value returned should: The Accumulative Swing Index uses a scale from 0 to 100 for an up trend and 0 to -100 for a down trend.

However, if you look here you will see the ASI image shows -50000, very odd.

http://forex-indicators.net/accumulative-swing-index

**Comment by joosthoeks** [comment]
I got the source calculation from the book: New Concepts in Technical Trading Systems. You can find a source calculation also from this url: https://www.fmlabs.com/reference/default.htm (indicator: Swing Index)

The SI should output values between -100 and 100. The ASI output can be different then the SI range.

Param L = value of a limit move in one direction. (page 90 of book: New Concepts in Technical Trading Systems)

Can you reproduce your error/issue and post the output?

**Comment by thegamecat** [comment]
I think you're calculations are correct, it's just I read something about ASI being 0-100, this is incorrect and your calculations look fine.
