### ISSUE TITLE
PSAR calculation is wrong 

### ISSUE THREAD

**Issue by mbmarx** [joosthoeks/jhTAlib#11]
The PSAR calculation is wrong the output is not matching with tradingview.com out put.

**Comment by joosthoeks** [comment]
I think you mean the SAR instead of PSAR?

I got the original SAR calculation from the book: New Concepts in Technical Trading Systems. On page: 9.

You can change the params: af_step (acceleration factor step) and af_max (acceleration factor max).

**Comment by joosthoeks** [comment]
closed
