### ISSUE TITLE
FIBOPR is NOT Fibonacci Price Retracements

### ISSUE THREAD

**Issue by macd2** [joosthoeks/jhTAlib#15]
This function does not calculate the price retracements. 

To get the retracements,  one need to calculate the fib levels from a range not a single price point.

**Comment by joosthoeks** [comment]
If you have a solution for this problem then you're welcome too do a PR for this. You can suggest also a different name for this method.

**Comment by macd2** [comment]
i have a working solution yes only "issue" is it introduces a new dependency.

But in general the fib levels are calculated from a range like  (localMax  - LocalMin)  so if you have a dependency free way to figure out logical maxima and minima than you can easily fix it. 

I don't know how to call this function as it is but it has surely nothing to do with Fibonacci Price Retracements.

**Comment by joosthoeks** [comment]
Fixed: https://github.com/joosthoeks/jhTAlib/commit/7af771e8beb5e04f87124c4c4656c4b6da59681c

**Comment by joosthoeks** [comment]
Refix: https://github.com/joosthoeks/jhTAlib/commit/8c0fdfa0e76e7e22bee69c1949e169b6e25af169
