### ISSUE TITLE
Harami Pattern detection is not working

### ISSUE THREAD

**Issue by gregnwosu** [joosthoeks/jhTAlib#7]
**Describe the bug**
harami detection is failing for the following dataframe

**To Reproduce**
```
import pandas as pd
import jhtalib

def test_harami():
    date_format = "%Y-%m-%d %H:%M:%S"
    df = pd.DataFrame(
        {
            EnumStandardCandleColumn.datetime.name: [
                "2015-01-27 13:22:03",
                "2015-01-28 13:23:03",
                "2015-01-29 13:24:03",
                "2015-01-30 13:25:03",
                "2015-01-31 13:26:03",
            ],
            "Open": [28.0, 38.0, 35.0, 68.0, 66.0],
            "High": [45.0, 66.0, 150.0, 60.0, 15.0],
            "Low": [20.0, 31.0, 20.0, 72.0, 68.0],
            "Close": [38.0, 55.0, 127.0, 66.0, 22.0],
            "Volume": [38.0, 55.0, 127.0, 66.0, 22.0]
        }
    )
    df["datetime"] = pd.to_datetime(df["datetime"], format=date_format)
    result = jhtalib.CDLHARAMI(h)
    assert result is not None
```

**Expected behavior**

**Screenshots**
The fourth candle from the left should be detected as harami
![image](https://user-images.githubusercontent.com/193151/57554657-f32bb900-7369-11e9-8a5a-e421f0125812.png)

**Desktop (please complete the following information):**
 - OS:macos
 - Browser n/a
 - Version jhtalib-20190328.0

**Additional context**

**Comment by joosthoeks** [comment]
The CDLHARAMI definition is not implemented yet.

**Comment by gregnwosu** [comment]
I can send a PR for this if you prefer

**Comment by joosthoeks** [comment]
Yes, you can do a pull request if it's only depends on the Python 3 standard library.

I would like to see an output for all pattern recognition definitions as follows:

If there is a bullish harami then output is 1
If there is a bearish harami then output is -1
Else (if no harami) output is 0

Also, if you can provide a source definition where we can check and validate the output would be very helpful. A source definition can be an online url with definition explanation or a book title where the source definition is defined.
