### ISSUE TITLE
Implementation for time series data

### ISSUE THREAD

**Issue by thegamecat** [joosthoeks/jhTAlib#8]
If I wish to implement say bbands for time series data - do I keep updating a dataframe per time tick and making the call the bbands function to get the outputs?

**Comment by joosthoeks** [comment]
If you want to calculate the last bbands output with n period of 10. Then you need minimum 10 last ticks.

**Comment by thegamecat** [comment]
Sorry that's not quite what I mean - I mean what do I pass into bbands per tick? An array of the last 200 close prices?

**Comment by joosthoeks** [comment]
I made a minimal basic usage example. You can find it here: https://colab.research.google.com/github/joosthoeks/jhTAlib/blob/master/example/example-11-basic-usage.ipynb

**Comment by thegamecat** [comment]
That is the perfect example, got it working within 60 seconds!

Thank you so much.
